name: Build Service

on:
  workflow_call:
    secrets:
      DEV_KEY:
        description: "Developer signing key"
        required: true

jobs:
  BuildPackage:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Prepare StartOS SDK
        uses: start9labs/sdk@v2

      - name: Checkout services repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build the service package
        id: build
        run: |
          mkdir -p ~/.startos
          printf '%s' "${{ secrets.DEV_KEY }}" > ~/.startos/developer.key.pem
          RUST_LOG=debug RUST_BACKTRACE=1 make
          PACKAGE_ID=$(start-cli s9pk inspect *.s9pk manifest | jq -r '.id')
          echo "package_id=${PACKAGE_ID}" >> $GITHUB_ENV
          printf "\n SHA256SUM: $(sha256sum ${PACKAGE_ID}.s9pk) \n"
        shell: bash

      - name: Upload .s9pk
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.package_id }}.s9pk
          path: ./${{ env.package_id }}.s9pk
